Feat/mui textinput
BlackBoxVision/react-final-form-helpers pull request #20
Opened 2021-01-31 22:38 UTC by manutuero

## Summary

- [x] Se agregó documentación al README file
- [x] Se implementó el componente `TextInput`
- [x] Se configuró Storybook usando **Component Story Format (CSF)** y **Typescript**

2021-01-31 22:56 UTC, JonatanSalas requested changes

2021-01-31 22:56 UTC, JonatanSalas commented on packages/rff-material-ui/src/index.tsx
> +export * from './components/TextInput';
No debería ser un archivo `index.tsx` sino `index.ts`, el `index.tsx` seria si hubiera codigo con JSX.

2021-01-31 22:56 UTC, JonatanSalas commented on packages/rff-material-ui/src/components/TextInput/index.tsx
> +      helperText={isError && meta.error}
Tendrías que hacer un if inline para poder pasarle un `helperText`

2021-01-31 22:56 UTC, JonatanSalas commented on packages/rff-material-ui/src/components/TextInput/index.tsx
> +export type TextInputProps = FieldRenderProps<string, any>;
Tenes que mergear las props de Typescript de Material UI con las de final form, de esa forma vas a poder tener todos los typings que se necesitan y el intellisense va a ser más preciso.

2021-01-31 22:56 UTC, JonatanSalas commented on packages/rff-material-ui/README.md
> +## Example Usage
Quizás teniendo Storybook apuntaría a una story para ver como se usa. Qué opinas?

2021-02-01 12:13 UTC, manutuero commented on packages/rff-material-ui/README.md
> +## Example Usage
Tengo la story, me faltó referenciarlo en el README. Ahora lo agrego

2021-02-01 16:36 UTC, merged